language: node_js
node_js:
  - 14.15.3

services:
  - docker

# Pre-testing installs
install:
  - echo "installing dependencies..."
  - npm install
  - echo "dependencies installed"

# Scripts to be run such as tests
before_script:
  - echo "running build command..."
  - ng build
  - echo "build completed"

script:
  - docker --version # print the version for logging
  - docker build -f Dockerfile -t meddy672/udagramfrontend .

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push meddy672/udagramfrontend:latest
